services:
  postgres:
    image: postgres:18
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: bd_payments

    ports:
      - "5000:5432"

    volumes:
      - pgdata:/var/lib/postgresql

    networks:
      - dokploy-network
      
networks:
  dokploy-network:
    external: true
