services:
  postgres:
    image: postgres:18
    container_name: pg18
    restart: always                # 🔥 se reinicia automáticamente al arrancar Docker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
